### ISSUE TITLE
Register for National Association of Government Web Professionals conference

### ISSUE THREAD

**Issue by daniel-coleman-1** [ONRR/nrrd#1977] opened 2022-02-14 16:34 UTC
Registration opens in April
https://nagw.org/

**Comment by daniel-coleman-1** [comment] 2022-02-14 17:43
Presentation proposals are due February 25:
https://nagw.org/2022_Call_for_Speakers

**Comment by Maroyafaied** [comment] 2022-03-03 16:46
@daniel-coleman-1 closing this issue since we missed the proposal deadline.

**Comment by lpgoldstein** [comment] 2022-03-03 18:03
presentations proposals are now due March 18

**Comment by Maroyafaied** [comment] 2022-03-14 22:26
@daniel-coleman-1 I confirmed that speakers have to attend in person so I'm closing this issue.

**Closed by Maroyafaied** 2022-03-14 22:26 UTC
Labels: outreach
