### ISSUE TITLE
Production/Gypsum error

### ISSUE THREAD

**Issue by jennmalcolm** [ONRR/nrrd#869] opened 2020-08-19 16:41 UTC
Going to production and choosing product "Gypsum" gives an error. There is gypsum production on Native American land only. I'm not sure if that's the cause of the issue. 

![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/b50e609c-6ba6-44b1-b117-b80682f7e0eb)

**Comment by mojobnichols** [comment] 2020-08-19 16:57
I added you to this PR: 
It was the same issue I found working with coal.  It is fixed in this PR,  I'll close this issue since it is a duplicate of 868

https://github.com/ONRR/nrrd/pull/870

**Closed by mojobnichols** 2020-08-19 16:57 UTC
Labels: P1: Showstopper
