### ISSUE TITLE
Explore Data: disbursements over time chart - scale off and data wrong

### ISSUE THREAD

**Issue by lpgoldstein** [ONRR/nrrd#403] opened 2020-05-06 21:43 UTC
Scale seems off and chart numbers distorted. Numbers also seem wrong.

![image](https://user-images.githubusercontent.com/39419003/81231126-a4d2e980-8fc0-11ea-88c4-af94c60c03f9.png)

**Comment by mcharg** [comment] 2020-05-11 13:42
Duplicate of #365

**Closed by mcharg** 2020-05-11 13:42 UTC
Labels: Explore Data, P1: Show Stopper
