### ISSUE TITLE
Native American production card showing location

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#451] opened 2020-05-18 21:25 UTC
There should not location associated with Native American data. 
![image](https://user-images.githubusercontent.com/40175688/82261179-cc5c7700-991b-11ea-8763-c3ac282b6975.png)

**Comment by mcharg** [comment] 2020-05-22 14:22
Duplicate of #438

**Closed by mcharg** 2020-05-22 14:22 UTC
Labels: Explore Data
