### ISSUE TITLE
 Gulf of Mexico Oil & Gas and total numbers are wrong

### ISSUE THREAD

**Issue by mcharg** [ONRR/nrrd#779] opened 2020-08-12 19:03 UTC
data issue Gulf of Mexico Oil & Gas and total numbers are wrong. ![image.png](https://images.zenhubusercontent.com/5c59c5bee180620812ea29eb/65f519c5-9859-4228-b925-c91a839d7e66)

**Comment by jennmalcolm** [comment] 2020-08-12 19:10
Other years are off as well for Gulf of Mexico. Since impacted commodity is oil & gas and impacted revenue types are rents, and other revenues.

![image](https://user-images.githubusercontent.com/30806839/90056910-a0982580-dcad-11ea-8d1f-b4fc52603b45.png)

**Comment by mojobnichols** [comment] 2020-08-13 15:43
This is caused by Gulf of mexico not being labled in spreadsheets consistently.   I had attempted to iron this out, but aparently some cases are missed.   I Have manually corrected for launch but I need to fix so next load it loads correctly.

**Comment by mcharg** [comment] 2020-08-13 16:26
@Maroyafaied Can you check dev to see if this issue is fixed?  We'll still keep this issue open to fix long-term, but want to make sure it's fixed in dev before hard launch.

**Comment by jennmalcolm** [comment] 2020-08-17 18:05
Temporary fix in dev, but permanent fix will be to fix load script to catch these in the future.

**Comment by Maroyafaied** [comment] 2020-08-18 15:17
@jennmalcolm the data is correct on the dev site for this issue.

**Comment by mcharg** [comment] 2021-03-04 16:35
Need to check to see if this is corrected in consolidated monthly file.

**Comment by mcharg** [comment] 2021-03-04 16:36
@Baymatt Can you check to see if this is corrected in the consolidated monthly file?

**Comment by mojobnichols** [comment] 2021-03-09 22:25
When I sum consolidatged monthly file  for Gulf of mexico Oil & Gas I get:  2,270,231,884.77

Can some one else verify that?   @Maroyafaied, @Baymatt @sghahn   

I will try to find out how site is arriving at:

![image.png](https://images.zenhubusercontent.com/5d1a3e771449416ed8985985/529aeab5-2c39-4216-9e43-25fbdccec75b)

**Comment by mojobnichols** [comment] 2021-03-09 22:52
I had originally put in the wrong graph I corrected the above graph.   So now I see that it matches so can we close this ticket? @sghahn @Maroyafaied

**Comment by Maroyafaied** [comment] 2021-03-09 23:18
@mojobnichols I checked CY 18 and it looks correct, you can go ahead and close it. 
![image](https://user-images.githubusercontent.com/40175688/110551626-16a12580-80f3-11eb-8c24-a75fb5776361.png)

**Closed** 2021-03-11 19:06 UTC
Labels: Explore Data, P2: High, bug
