### ISSUE TITLE
Explain Tickets/Pounds

### ISSUE THREAD

**Issue by Maroyafaied** [ONRR/nrrd#570] opened 2020-06-09 17:20 UTC
The changes in this pull request did not make it the NRRD repo. 

https://github.com/ONRR/doi-extractives-data/pull/4878
Changes proposed in this pull request:

Adds glossary term for tickets/pounds
Adds documentation question for tickets/pounds

**Comment by jennmalcolm** [comment] 2020-06-24 17:46
duplicate of #569

**Closed by jennmalcolm** 2020-06-24 17:46 UTC
